# Ip Address Either Gateway Or OMS
ip: 10.0.10.146

# Connecting Port
port: 8888

# Is Placing Request To GW or OMS
isGWClient: true

# Number Of End Points
numOfEndPoints: 120

# Public Gateway Ip
orderPlaceViaPublicGW:
    isEnable: true
    url: ws://130.61.76.85/streaming-api

# Restricted Trade Account Ids
restrictedTrdIDS: 32,33,64

# Order Placing Settings
ordersPerTimeSlice:
    isEnable: true
    orderPerSlice: 1000
    timePeriod: 1

# Account Details File Name
textLocation: AccountDetails.txt

# Request Placing Dealer Details
dealerDetails:
    dealerId: 6
    loginName: prakashdt
    password: a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
